blog/urls.py
from django.conf.urls import patterns, url

from models import Post

urlpatterns = patterns('',
    url(r'^post/(?P<slug>[-\w]+)$', 'blog.views.view_post', name='blog_post_detail'),
    url(r'^add/post$', 'blog.views.add_post', name='blog_add_post'),
)

serverfail/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'serverfail.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^accounts/login/$', 'django.contrib.auth.views.login'),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^blog/', include('blog.urls'))
)

blog/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=140)
    slug = models.SlugField(unique=True)
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User)
    
    def __unicode__(self):
        return self.title
    
    @models.permalink
    def get_absolute_url(self):
        return('blog_post_detail', (),
               {
                    'slug' :self.slug,
                })
        
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)
        

class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=60)
    website = models.URLField(max_length=200, null=True, blank=True)
    text = models.TextField()
    post = models.ForeignKey(Post)
    created_on = models.DateField(auto_now_add=True)
    
    def __unicode__(self):
        return self.text
    

blog/forms.py
from django import forms
from models import Post, Comment

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        exclude = ['author', 'slug']
        
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ['post']
        

blog/views.py
from django.contrib.auth.decorators import user_passes_test
from django.shortcuts import redirect, render_to_response, get_object_or_404
from django.template import RequestContext

from models import Post
from forms import PostForm, CommentForm
from django.core.context_processors import request
from django.db.transaction import commit

# Create your views here.

@user_passes_test(lambda u: u.is_superuser)
def add_post(request):
    form = PostForm(request.POST or None)
    
    if form.is_valid():
        post = form.save(commit=False)
        post.autor = request.user
        post.save()
        
        return redirect(form)
    
    return render_to_response( 'blog/add_post.html', { 'form': form }, context_instace=RequestContext(request) )



def view_post(request, slug):
    post = get_object_or_404(Post, slug=slug)
    form = CommentForm(request.POST or None)
    
    if form.is_valid():
        comment = form.save(commit(False))
        comment.post = post
        comment.save()
        request.session["name"] = comment.name
        request.session["email"] = comment.email
        request.session["website"] = comment.website
        
        return redirect(request.path)
    
    return render_to_response('blog/blog_post.html',
                       {
                            'post': post,
                            'form': form,
                        },
                       context_instance=RequestContext(request))
    

blog/templates/archive_mounth.html
<h2>Post archives for {{ month|date:"F" }}, {{ month|date:"Y" }}</h2>

<ul>
    {% for post in object_list %}
        <li>
        <a href="{% url blog_post_detail post.slug %}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

blog/templates/archive_week.html
<h2>Post archives for week {{ week|date:"W" }}, {{ week|date:"Y" }}</h2>

<ul>
    {% for post in object_list %}
        <li>
        <a href="{% url blog_post_detail post.slug %}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

blog/templates/blog/add_post.html
<h2>Hello {{ user.username }}</h2>
<br />
<h2>Add new post</h2>
<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" name="add" value="Add" />
</form>

blog/templates/blog/blog_post.html
<h2>{{ post.title }}</h2>

<div class="content">
    <p>
        {{ post.text }}
    </p>
    <span>
        Written by {{ post.author }}  on {{ post.created_on }}
    </span>
</div>

{% if post.comment_set.all %}
<h2>Comments</h2>
<div class="comments">
    {% for comment in post.comment_set.all %}
        <span>
            <a href="{{ comment.website }}">{{ comment.name }}</a> said on {{ comment.created_on }}
        </span>
        <p>
            {{ comment.text }}
        </p>
    {% endfor %}
</div>
{% endif %}

<br />

<h2>Add Comment</h2>

<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" name="submit" value="Submit" />
</form>